-- Table: clicks
create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  link_id uuid references links(id) on delete cascade,
  timestamp timestamptz default now(),
  referrer text,
  device text
);
