-- Table: leads
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  link_id uuid references links(id) on delete cascade,
  email text not null,
  consent boolean default true,
  timestamp timestamptz default now()
);
